version : '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    volumes:
      - ./src/example-app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8070:80"
    depends_on:
      - mysql
      - php
    networks:
      - laravel
  mysql:
    image: mysql:5.7.4
    container_name: mysql--container
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - laravel
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  php:
    build:
      args:
        user: ahmad
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    working_dir: /var/www/html
    volumes:
      - ./src/example-app:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - laravel


#Docker Networks
networks:
  laravel: